name: Publish artifacts

on:
  release:
    types:
        - created

jobs:
  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    env:
      name: rpi-provisioner
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.4'

      - name: Build
        run: make build

      - name: List files
        run: ls -l build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          draft: false
