name: Build artifacts

on:
  pull_request:

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.4'

      - name: Build
        run: make clean build

      - name: List files
        run: ls -l build
