# workflow name
name: Generate release-artifacts

# on events
on:
  pull_request:

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    env:
      name: rpi-provisioner
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.4'

      - name: Build
        run: make build

      - name: List files
        run: ls -l build
